[project]
name = "ckmetrics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "networkx>=3.4.2",
]

[project.scripts]
ckmetrics = "ckmetrics:start"

[tool.uv]
package = true